cargo-features = ["codegen-backend"]

[package]
name = "pro-se"
version = "0.1.0"
edition = "2024"

[dependencies]
avian3d = { version = "0.7", features = ["simd"] }
bevy_enhanced_input = "0.26"
bevy_framepace = "0.22"
bevy_seedling = { version = "0.8", default-features = false, features = [
    "reflect",
    "rand",
    "cpal",
    "hrtf",
    "hrtf_subjects",
    "ogg",
] }
bevy_skein = { version = "0.6", default-features = false }
bevy_sprinkles = "0.3"
bevy_transform_interpolation = "0.5"
log = { version = "*", features = [
    "max_level_debug",
    "release_max_level_warn",
] }
mimalloc-redirect = "*"
rand = "0.10"
ron = "0.12"
serde = { version = "1", features = ["derive"] }
smallvec = { version = "1", features = [
    "const_generics",
    "const_new",
    "union",
] }
symphonia-adapter-libopus = "0.3"
tracing = { version = "*", features = [
    "max_level_debug",
    "release_max_level_warn",
] }

[dependencies.bevy]
version = "0.19"
default-features = false
features = [
    "default_app",
    "default_platform",
    "3d_bevy_render",
    "ui_bevy_render",
    "scene",
    "picking",
    "pbr_transmission_textures",
]

[features]
default = ["dev"]
dev = [
    "bevy/dev",
    "bevy/default_font",
    "bevy_skein/brp",
    "bevy_skein/presets",
    "bevy_seedling/dev",
    "bevy_seedling/entity_names",
    "bevy_seedling/diagnostics",
]

[profile.dev]
codegen-backend = "cranelift"
incremental = true
lto = "off"
debug = "line-tables-only"

[profile.dev.package."*"]
codegen-backend = "llvm"
opt-level = 2
debug-assertions = true
debug = "none"

[profile.release]
codegen-backend = "llvm"
codegen-units = 1
incremental = false
lto = "fat"
strip = true
debug = 0
